services:
  traefik:
    image: traefik:v3.4.5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - ./docker/traefik/dynamic/:/etc/traefik/dynamic/:ro
      - ./docker/traefik/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - web
    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.filename=/etc/traefik/dynamic/traefik_dynamic.yml"

      # Providers 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${NETWORK_NAME}"

      # API & Dashboard 
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability 
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"

    # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
      # - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$0B/Dz.El$$GnZpNWj.sHjWmc888iwQn."
      # - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"


  auth_app:
    build: ./auth/docker/php/8.4
    depends_on:
      - auth_db
    volumes:
      - ./auth/src:/var/www/html
    networks:
      - web

  nginx:
    image: nginx:alpine
    depends_on:
      - auth_app
    volumes:
      - ./auth/scr:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`${AUTH_DOMAIN}`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
    networks:
      - web

  auth_db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - ./auth/storage/auth_db:/var/lib/postgresql
    networks:
      - web

networks:
  web:
    name: ${NETWORK_NAME}
    external: false
